name: Compile and release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Build x86_64
        run: |
          make TARGET=cbr-linux-x86_64

      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            cbr-linux-x86_64
